name: personal_voice_flutter
description: This project uses the iOS personal voice to speak text in your own voice.
version: 0.0.2
homepage: https://github.com/rockarts/personal_voice_flutter

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: PersonalVoiceFlutterPlugin
