name: flutter_vocalizer
description: Provides text to speech capabilities on iOS and Android. iOS 17+ for personal voice to speak text in your own voice. SSML support.
version: 1.0.0+1
homepage: https://github.com/normano/flutter_vocalizer

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.excsn.flutter_vocalizer
        pluginClass: FlutterVocalizerPlugin
      ios:
        pluginClass: FlutterVocalizerPlugin
